// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingAssistant.Infrastructure.Persistence;

#nullable disable

namespace TrainingAssistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524223238_AddPlanEnhancements")]
    partial class AddPlanEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("numeric");

                    b.Property<int>("DefaultPortionGrams")
                        .HasColumnType("integer");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<Guid>("NutritionDayId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutritionDayId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grams")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlternative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.NutritionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCarbsG")
                        .HasColumnType("integer");

                    b.Property<int>("TargetFatG")
                        .HasColumnType("integer");

                    b.Property<int>("TargetProteinG")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyPlanId", "DayIndex")
                        .IsUnique();

                    b.ToTable("NutritionDays");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.TrainingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyPlanId", "DayIndex")
                        .IsUnique();

                    b.ToTable("TrainingDays");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.TrainingExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestSec")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingDayId");

                    b.ToTable("TrainingExercises");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.UserExercisePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvoidExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PoolKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreferredExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AvoidExerciseName")
                        .IsUnique();

                    b.ToTable("UserExercisePreferences");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<string>("InjuriesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionDurationMin")
                        .HasColumnType("integer");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingFocus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("ProgramConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ProgramType")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.Meal", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.NutritionDay", "NutritionDay")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionDay");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingAssistant.Domain.Entities.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.NutritionDay", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("NutritionDays")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.TrainingDay", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("TrainingDays")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.TrainingExercise", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.TrainingDay", "TrainingDay")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingDay");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.UserExercisePreference", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("TrainingAssistant.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.WeeklyPlan", b =>
                {
                    b.HasOne("TrainingAssistant.Domain.Entities.User", "User")
                        .WithMany("WeeklyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.NutritionDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.TrainingDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("WeeklyPlans");
                });

            modelBuilder.Entity("TrainingAssistant.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Navigation("NutritionDays");

                    b.Navigation("TrainingDays");
                });
#pragma warning restore 612, 618
        }
    }
}
